### ISSUE TITLE
Fix Elasticsearch issues

### ISSUE THREAD

**Issue by jaywhy13** [jaywhy13/django-whatyouspend#27]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 62, in _wrapper
>     return bound_func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
>     return view_func(request, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 58, in bound_func
>     return func.__get__(self, type(self))(*args2, **kwargs2)
>   File "/code/whatyouspend/transactions/mixins.py", line 28, in dispatch
>     return super(TransactionsViewMixin, self).dispatch(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
>     return handler(request, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/views/generic/list.py", line 142, in get
>     self.object_list = self.get_queryset()
>   File "/code/whatyouspend/transactions/views.py", line 88, in get_queryset
>     return search_results.to_queryset()
>   File "/usr/local/lib/python3.6/site-packages/django_elasticsearch_dsl/search.py", line 28, in to_queryset
>     pks = [result._id for result in s]
>   File "/usr/local/lib/python3.6/site-packages/elasticsearch_dsl/search.py", line 306, in __iter__
>     return iter(self.execute())
>   File "/usr/local/lib/python3.6/site-packages/elasticsearch_dsl/search.py", line 679, in execute
>     **self._params
>   File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
>     return func(*args, params=params, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 655, in search
>     doc_type, '_search'), params=params, body=body)
>   File "/usr/local/lib/python3.6/site-packages/elasticsearch/transport.py", line 318, in perform_request
>     status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
>   File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 185, in perform_request
>     self._raise_error(response.status, raw_data)
>   File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
>     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
> elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', 'Fielddata is disabled on text fields by default. Set fielddata=true on [transaction_type] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.')

**Comment by jaywhy13** [comment]
This is only happening on Jenkins.

**Comment by jaywhy13** [comment]
Seems to happen if we don't build the index explicitly. If the index is built as a result of a transaction added, then it doesn't create the index properly and it uses a text field apparently for the `transaction_type` field.
